import { useSupabaseClient } from "@supabase/auth-helpers-react"
import { useToast } from "@/hooks/use-toast"
import type { Candidate } from "@/types/candidate"

export function useSendVideoInvites(jobId: string) {
  const supabase = useSupabaseClient()
  const { toast } = useToast()

  const sendVideoInvites = async (selectedIds: string[], candidates: Candidate[]) => {
    if (!jobId || selectedIds.length === 0) {
      toast({
        title: "Error",
        description: "No candidates selected",
        variant: "destructive",
      })
      return false
    }

    try {
      const selectedCandidates = candidates.filter(c => selectedIds.includes(c.id))
      
      for (const candidate of selectedCandidates) {
        // Update status to 'requested' when sending invite
        const { error: updateError } = await supabase
          .from('candidates')
          .update({ status: 'requested' })
          .eq('id', candidate.id)

        if (updateError) {
          console.error('Error updating candidate status:', updateError)
          continue
        }

        // The token is automatically generated by the database trigger
        const { data: updatedCandidate, error } = await supabase
          .from('candidates')
          .select('video_token')
          .eq('id', candidate.id)
          .single()

        if (error) {
          console.error('Error fetching candidate token:', error)
          continue
        }

        const videoToken = updatedCandidate.video_token
        if (!videoToken) {
          console.error('No video token found for candidate:', candidate.id)
          continue
        }

        // Call the send_video_invite function
        const { error: inviteError } = await supabase
          .rpc('send_video_invite', {
            payload: {
              candidate_id: candidate.id,
              video_token: videoToken,
              candidate_name: candidate.name,
              candidate_email: candidate.email,
              candidate_phone: candidate.phone
            }
          })

        if (inviteError) {
          console.error('Error sending invite:', inviteError)
          toast({
            title: "Error",
            description: `Failed to send invite to ${candidate.name}`,
            variant: "destructive",
          })
          continue
        }
      }

      toast({
        title: "Success",
        description: `Sent ${selectedIds.length} video invites`,
      })
      return true
    } catch (error) {
      console.error('Error in sendVideoInvites:', error)
      toast({
        title: "Error",
        description: "Failed to send video invites",
        variant: "destructive",
      })
      return false
    }
  }

  return {
    sendVideoInvites
  }
}