// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elirvptqddqsscylwczk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaXJ2cHRxZGRxc3NjeWx3Y3prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NTYzNjksImV4cCI6MjA1MjIzMjM2OX0.i246K5CdY8z7Xu5WUJ4m8xII9xR9fBSE0tEb_-_8sxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);